export const TODOS_ARRAY = [
  "Start your day with a morning routine that energizes you.",
  "Dedicate time to deep work sessions without distractions.",
  "Read books from various genres to expand your perspective.",
  "Practice mindfulness or meditation to enhance focus and clarity.",
  "Set clear, achievable goals for both short-term and long-term.",
  "Maintain a healthy work-life balance to nurture creativity.",
  "Exercise regularly to boost physical health and mental well-being.",
  "Network with professionals from different fields to broaden your understanding.",
  "Learn a new language or skill to challenge your brain.",
  "Adopt a growth mindset, viewing challenges as opportunities to grow.",
  "Volunteer for causes you care about to give back to the community.",
  "Take up a hobby unrelated to your work to foster creativity.",
  "Practice gratitude by reflecting on what you're thankful for each day.",
  "Travel to new places to gain fresh perspectives and inspiration.",
  "Engage in regular self-reflection to understand your values and aspirations.",
  "Prioritize sleep to ensure you're well-rested and alert.",
  "Develop a strong support system of friends and family.",
  "Stay hydrated and eat nutritiously to fuel your body and mind.",
  "Set boundaries to protect your time and energy.",
  "Embrace lifelong learning, always seeking to expand your knowledge.",
  "Cultivate patience, recognizing that growth takes time.",
  "Listen actively when others speak to learn and understand better.",
  "Keep an idea journal to capture moments of inspiration.",
  "Attend workshops and seminars on personal development topics.",
  "Practice effective time management to make the most of your day.",
  "Seek out mentors who can guide and inspire you.",
  "Be adaptable, ready to pivot or change strategies when necessary.",
  "Celebrate your achievements, no matter how small they may seem.",
  "Develop resilience, learning to bounce back from setbacks.",
  "Show kindness and compassion to yourself and others.",
  "Foster a sense of curiosity, always asking questions and exploring.",
  "Invest in personal relationships, building strong connections.",
  "Learn to manage stress through healthy outlets.",
  "Challenge yourself regularly to step out of your comfort zone.",
  "Cultivate a positive attitude, focusing on solutions rather than problems.",
  "Be proactive, taking initiative in your personal and professional life.",
  "Practice financial responsibility, planning for the future while enjoying the present.",
  "Engage in creative activities to express yourself and unwind.",
  "Prioritize tasks based on importance and urgency to stay productive.",
  "Learn to say no when necessary to focus on what truly matters.",
  "Seek balance in all aspects of life, from work to leisure.",
  "Stay organized to reduce stress and increase efficiency.",
  "Reflect on your experiences, learning from both successes and failures.",
  "Engage in community service to connect with others and make a difference.",
  "Take time for self-care, recognizing its importance for overall well-being.",
  "Be open to feedback, using it as a tool for growth.",
  "Stay informed about the world around you, understanding its complexities.",
  "Explore different cultures to appreciate diversity and gain empathy.",
  "Practice effective communication, both in speaking and writing.",
  "Build confidence by facing fears and taking on new challenges.",
  "Maintain a sense of humor, finding joy and laughter in everyday life.",
  "Be mindful of your digital consumption, taking breaks from screens.",
  "Cultivate creativity, seeking inspiration in the world around you.",
  "Foster independence, trusting in your abilities and making your own decisions.",
  "Stay humble, recognizing there's always more to learn.",
  "Appreciate the small moments, finding beauty in the everyday.",
  "Develop a routine that supports your goals and well-being.",
  "Stay committed to your values, letting them guide your actions.",
  "Embrace change, seeing it as an opportunity for growth.",
  "Build resilience by cultivating a strong sense of self.",
  "Practice empathy, striving to understand others' perspectives.",
  "Invest in your personal growth, dedicating time to activities that enrich you.",
  "Celebrate diversity, recognizing the strength it brings to communities.",
  "Prioritize mental health, seeking support when needed.",
  "Be environmentally conscious, making sustainable choices.",
  "Cultivate a global mindset, understanding your impact on the world.",
  "Explore your passions, allowing them to guide your path.",
  "Practice self-discipline, staying focused on your objectives.",
  "Maintain a sense of wonder, always looking to discover and learn.",
  "Be authentic, true to yourself in all aspects of life.",
  "Foster a spirit of generosity, sharing your time and resources.",
  "Cultivate leadership skills, inspiring and guiding others.",
  "Stay grounded, finding stability in a fast-paced world.",
  "Be visionary, setting bold goals and working towards them.",
  "Practice kindness, making the world a better place one act at a time.",
  "Stay connected with nature, appreciating its beauty and power."
]